### ISSUE TITLE
Scrolling doesnt cover entire content

### ISSUE THREAD

**Issue by nikelasi** [swiftaccelerator2020/CATmistry#35]
version: v1.0.0
device: iPhone SE (2nd gen)
platform: iOS 14.2
a bug where if the content is too large, scrolling won't work properly and you have to drag on the scrollbar to view the rest of the content
[Video](https://drive.google.com/file/d/1u3_nqsydQdJYoLADBtMshSsoDGRvCKfi/view?usp=sharing)

**Comment by neohaojun** [comment]
resolved
