### ISSUE TITLE
Games don't unlock upon completion of chapter

### ISSUE THREAD

**Issue by nikelasi** [swiftaccelerator2020/CATmistry#36]
version: v1.0.0
device: iPhone SE (2nd gen)
platform: iOS 14.2
After completing a chapter, the games won't be unlocked despite a 10/10 score quiz, it will only unlock after restarting the app.
![Chapter1 completed](https://user-images.githubusercontent.com/58451243/102615122-5994d200-4170-11eb-967d-e845dfdd1a9a.png)
![Chapter1 game not unlocked](https://user-images.githubusercontent.com/58451243/102615126-5ac5ff00-4170-11eb-98b1-bd4f4f65fc56.png)

**Comment by theriseof9** [comment]
fixed
