### ISSUE TITLE
Settings doesn't save, info button doesn't work

### ISSUE THREAD

**Issue by nikelasi** [swiftaccelerator2020/CATmistry#37]
version: v1.0.0
device: iPhone SE (2nd gen)
platform: iOS 14.2
Making any changes in settings doesn't save the settings and the information button on the amount of retries does nothing
[Video](https://drive.google.com/file/d/12ji8F4WVBFOEiWCMeHuSsXK2em532r_h/view?usp=sharing)

**Comment by theriseof9** [comment]
fixed, the information button is just a icon
