### ISSUE TITLE
Multiple issues with gas test game

### ISSUE THREAD

**Issue by nikelasi** [swiftaccelerator2020/CATmistry#38]
version: v1.0.0
device: iPhone SE (2nd gen)
platform: iOS 14.2

bugs:
1. correct answer is wrong
2. seems to have a bias towards hydrogen test (might be coincidence)
3. timer sometimes skips a second (happens in gas test + pH test game afaik)

ui suggestions:
1. if a gas tank was selected in a previous round, the next round, it is still selected and the button to submit is missing (instead of remaining selected, unselect it)
2. the cat can have a transparent background instead of the awkward white

video might not cover all bugs but the bugs should be reproducible just by playing the game casually
[Video](https://drive.google.com/file/d/1mty7GbdZFG6lKHudCEB509vzDEL2EolF/view?usp=sharing)

**Comment by theriseof9** [comment]
fixed
