### ISSUE TITLE
other issues that doesn't deserve their own issue

### ISSUE THREAD

**Issue by nikelasi** [swiftaccelerator2020/CATmistry#42]
version: v1.0.0
device: iPhone SE (2nd gen)
platform: iOS 14.2

1. spelling in Separation Methods > What is Separation? > Evaporation
2. the answer for Chapter4: "Where are the metal elements found in the periodic table?" may be wrong
3. mispelling in README "Authors and Acknoledgements"

**Comment by neohaojun** [comment]
resovled mispelling in README in the `edit-readme` branch

**Comment by theriseof9** [comment]
fixed the answer for Chapter4: "Where are the metal elements found in the periodic table?" may be wrong

**Comment by theriseof9** [comment]
fixed all
