### ISSUE TITLE
Gas Test Game Bug

### ISSUE THREAD

**Issue by nikelasi** [swiftaccelerator2020/CATmistry#53]
App Version: v1.1.0
Device: iPhone SE (2nd Gen)
Platform: iOS 14.2

By the off chance, when selecting the litmus paper, the tests come out true for 2 tanks. And it's a 50-50 chance to get it right
![image](https://user-images.githubusercontent.com/58451243/102728572-937bf900-4367-11eb-89e7-1f27af94b6dd.png)

**Comment by theriseof9** [comment]
oops sorry, fixed. 
(time to kill data ppl)
